; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:cabin_lora]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

; Fixed Port (Cabin)
; upload_port = COM8
; monitor_port = COM8

; Flash Memory Settings
; Force 4MB to match detected flash size and avoid errors.
; If you verify your board has 8MB/16MB, change this later.
board_upload.flash_size = 4MB
board_build.partitions = huge_app.csv

build_flags = 
    ; Enable USB Serial (CDC)
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    
    ; Define Built-in LED name (avoid using LED_BUILTIN to prevent conflicts)
    -DRAD_LED=37

    ; Pin Definitions for LilyGo T3S3 SX1280
    -DSX1280_SCK=5
    -DSX1280_MISO=3
    -DSX1280_MOSI=6
    -DSX1280_CS=7
    -DSX1280_RST=8
    -DSX1280_DIO1=9
    -DSX1280_BUSY=36
    
    ; Enables PA/LNA (Required for some T3S3 versions)
    -DSX1280_RXEN=21
    -DSX1280_TXEN=10

lib_deps = 
    jgromes/RadioLib @ ^6.6.0
